Improved multithreading
erikas-taroza/redshelf_downloader pull request #4
Opened 2024-08-28 02:33 UTC by JakeG2004

I added a basic version of multi threading that allows any number of threads to be used, not just a divisor of the pages.

Essentially:
1) Divide up pages to nearest whole number / thread
2) go through n-1 threads, processing pages as normal
3) for the n thread, process its number of pages plus the remaining pages

2024-08-29 22:08 UTC, erikas-taroza requested changes
Hello. Thank you for your PR. I have some changes I want you to make to make the code more simple and reduce redundancy.

2024-08-29 22:08 UTC, erikas-taroza commented on README.md
> +This fork has an improved version of multithreading
Remove this line.

2024-08-29 22:08 UTC, erikas-taroza commented on scrape.py
> +#assert(NUM_PAGES % NUM_THREADS == 0)
You can delete this assertion since its not necessary anymore

2024-08-29 22:08 UTC, erikas-taroza commented on scrape.py
> +def multi_thread():
No need to make this a new method. Just keep the same as before. You can wrap the for loop with an if statement checking if NUM_THREADS > 1

2024-08-29 22:08 UTC, erikas-taroza commented on scrape.py
> +    thread = threading.Thread(target=download_thread, args=(start, NUM_PAGES + 1))
I believe adding 1 to NUM_PAGES will make it attempt to fetch a page that doesnt exist. The page index on redshelf starts at 1, not 0.

2024-08-29 22:08 UTC, erikas-taroza commented on scrape.py
> +def single_thread():
Unnecessary method

2024-08-29 22:31 UTC, JakeG2004 reviewed
Implemented changes

2024-08-29 22:31 UTC, JakeG2004 commented on scrape.py
> +    thread = threading.Thread(target=download_thread, args=(start, NUM_PAGES + 1))
In my experience, it would miss the last page without the plus one depending on how many threads I had running. It also never caused any issuess

2024-08-30 03:18 UTC, erikas-taroza commented on scrape.py
> +    thread = threading.Thread(target=download_thread, args=(start, NUM_PAGES + 1))
Ill try on my end then with different amounts of threads.

2024-08-30 03:22 UTC, erikas-taroza requested changes

2024-08-30 03:22 UTC, erikas-taroza commented on scrape.py
> +if(NUM_THREADS > 1):
Sorry. Let me clarify. This if statement should only wrap the for loop, not the code below the for loop. For example:

```py
if (NUM_THREADS > 1):
    for i in range(0, NUM_THREADS - 1):
        pass

thread = threading. Thread...
```

Do this for both of the loops for download and convert and then we don't need the extra code wrapped by the ``if(NUM_THREADS == 1)``

2024-08-30 03:22 UTC, erikas-taroza commented on scrape.py
> +if(NUM_THREADS == 1):
Unnecessary code, see other comment.

2025-01-26 07:16 UTC, erikas-taroza commented
Hey. This is a pretty old PR with no activity. I implemented this logic in 9a0452e so I will close this.

2025-01-26 07:16 UTC, closed without merging